/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.mbte.gretty.cassandra.thrift;

public class Constants {

  public static final String VERSION = "2.2.0";

}
